// app/layout.tsx
import { getServerSession } from "next-auth/next";
import { authOptions } from '@/lib/authOptions'; // Ensure the path is correct
import SessionProviderWrapper from '@/components/SessionProviderWrapper';
import ClientLayout from '@/components/ClientLayout';
import { Poppins } from 'next/font/google';
import './globals.css'; // Ensure global styles are imported

import { Metadata } from 'next';
import { ToastContainer } from "react-toastify";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // Fetch the session server-side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProviderWrapper session={session}>
          <ClientLayout>
          <ToastContainer 
                position="top-right"
                autoClose={2000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            {children}</ClientLayout>
        </SessionProviderWrapper>
      </body>
    </html>
  );
};

export default RootLayout;

