// app/layout.tsx
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions"; // Ensure the path is correct
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import ClientLayout from "@/components/ClientLayout";
import { Poppins } from "next/font/google";
import "./globals.css"; // Ensure global styles are imported
import StoreProvider from "../../StoreProvider/StoreProvider";
import { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // Fetch the session server-side
  const session = await getServerSession(authOptions);

  return (
    <StoreProvider>
      <html lang="en">
        <body className={poppins.className}>
          <SessionProviderWrapper session={session}>
            <ClientLayout>
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
              {children}
            </ClientLayout>
          </SessionProviderWrapper>
        </body>
      </html>
    </StoreProvider>
  );
};

export default RootLayout;
