import React from 'react';
import Header from './Header';
import Headerbottom from './Headerbottom';
import Headertop from './Headertop';
import Bb from './bb';
import { GetStaticProps } from 'next';

interface MainLayoutProps {
  children: React.ReactNode;
  categories: Category[];
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Category {
  id: string;
  name: string;
  logoUrl: string;
}

const MainLayout: React.FC<MainLayoutProps> = ({ children, categories }) => {
  return (
    <div>
      <Headertop />
      <Header categories={categories} />
      <Headerbottom categories={categories} />
      {children}     
      <Bb />
    </div>
  );
};



export default MainLayout;
