const Governorate = [
  { id: 1, name: " Tunis" },
  { id: 2, name: " Sfax" },
  { id: 3, name: " Sousse" },
  { id: 4, name: " Kairouan" },
  { id: 5, name: " Bizerte" },
  { id: 6, name: " Gabès" },
  { id: 7, name: " l'Ariana" },
  { id: 8, name: " Ben Arous" },
  { id: 9, name: " Gafsa" },
  { id: 10, name: " Monastir" },
  { id: 11, name: " Nabeul" },
  { id: 12, name: " Médenine" },
  { id: 13, name: " Tataouine" },
  { id: 14, name: " Kasserine" },
  { id: 15, name: " la Manouba" },
  { id: 16, name: " Béja" },
  { id: 17, name: " Siliana" },
  { id: 18, name: " Zaghouan" },
  { id: 19, name: " Kébili" },
  { id: 20, name: " Jendouba" },
  { id: 21, name: " Mahdia" },
  { id: 22, name: " Sidi Bouzid" },
  { id: 23, name: " Tozeur" },
  { id: 24, name: " Kef" },
];

const city = [
  { id: 1, name: "Bab El Bhar", governorate_id: 1 },
  { id: 2, name: "Bab Souika", governorate_id: 1 },
  { id: 3, name: "Carthage", governorate_id: 1 },
  { id: 4, name: "Cité El Khadra", governorate_id: 1 },
  { id: 5, name: "Djebel Jelloud", governorate_id: 1 },
  { id: 6, name: "El Kabaria", governorate_id: 1 },
  { id: 7, name: "El Menzah", governorate_id: 1 },
  { id: 8, name: "El Omrane", governorate_id: 1 },
  { id: 9, name: "El Omrane supérieur", governorate_id: 1 },
  { id: 10, name: "El Ouardia", governorate_id: 1 },
  { id: 11, name: "Ettahrir", governorate_id: 1 },
  { id: 12, name: "Ezzouhour", governorate_id: 1 },
  { id: 13, name: "Hraïria", governorate_id: 1 },
  { id: 14, name: "La Goulette", governorate_id: 1 },
  { id: 15, name: "La Marsa", governorate_id: 1 },
  { id: 16, name: "Le Bardo", governorate_id: 1 },
  { id: 17, name: "Le Kram", governorate_id: 1 },
  { id: 18, name: "La Médina", governorate_id: 1 },
  { id: 19, name: "Séjoumi", governorate_id: 1 },
  { id: 20, name: "Sidi El Béchir", governorate_id: 1 },
  { id: 21, name: "Sidi Hassine", governorate_id: 1 },
  { id: 22, name: "Agareb", governorate_id: 2 },
  { id: 23, name: "Bir Ali Ben Khalifa", governorate_id: 2 },
  { id: 24, name: "El Amra", governorate_id: 2 },
  { id: 25, name: "El Hencha", governorate_id: 2 },
  { id: 26, name: "Graïba", governorate_id: 2 },
  { id: 27, name: "Jebiniana", governorate_id: 2 },
  { id: 28, name: "Kerkennah", governorate_id: 2 },
  { id: 29, name: "Mahrès", governorate_id: 2 },
  { id: 30, name: "Menzel Chaker", governorate_id: 2 },
  { id: 31, name: "Sakiet Eddaïer", governorate_id: 2 },
  { id: 32, name: "Sakiet Ezzit", governorate_id: 2 },
  { id: 33, name: "Sfax Ouest", governorate_id: 2 },
  { id: 34, name: "Sfax Sud", governorate_id: 2 },
  { id: 35, name: "Sfax Ville", governorate_id: 2 },
  { id: 36, name: "Skhira", governorate_id: 2 },
  { id: 37, name: "Thyna", governorate_id: 2 },
  { id: 38, name: "Akouda", governorate_id: 3 },
  { id: 39, name: "Bouficha", governorate_id: 3 },
  { id: 40, name: "Enfida", governorate_id: 3 },
  { id: 41, name: "Hammam Sousse", governorate_id: 3 },
  { id: 42, name: "Hergla", governorate_id: 3 },
  { id: 43, name: "Kalâa Kebira", governorate_id: 3 },
  { id: 44, name: "Kalâa Seghira", governorate_id: 3 },
  { id: 45, name: "Kondar", governorate_id: 3 },
  { id: 46, name: "M'saken", governorate_id: 3 },
  { id: 47, name: "Sidi Bou Ali", governorate_id: 3 },
  { id: 48, name: "Sidi El Hani", governorate_id: 3 },
  { id: 49, name: "Sousse Jawhara", governorate_id: 3 },
  { id: 50, name: "Sousse Médina", governorate_id: 3 },
  { id: 51, name: "Sousse Riadh", governorate_id: 3 },
  { id: 52, name: "Sousse Sidi Abdelhamid", governorate_id: 3 },
  { id: 53, name: "Bou Hajla", governorate_id: 4 },
  { id: 54, name: "Chebika", governorate_id: 4 },
  { id: 55, name: "Echrarda", governorate_id: 4 },
  { id: 56, name: "El Alâa", governorate_id: 4 },
  { id: 57, name: "Haffouz", governorate_id: 4 },
  { id: 58, name: "Hajeb El Ayoun", governorate_id: 4 },
  { id: 59, name: "Kairouan Nord", governorate_id: 4 },
  { id: 60, name: "Kairouan Sud", governorate_id: 4 },
  { id: 61, name: "Nasrallah", governorate_id: 4 },
  { id: 62, name: "Oueslatia", governorate_id: 4 },
  { id: 63, name: "Sbikha", governorate_id: 4 },
  { id: 64, name: "Bizerte Nord", governorate_id: 5 },
  { id: 65, name: "Bizerte Sud", governorate_id: 5 },
  { id: 66, name: "El Alia", governorate_id: 5 },
  { id: 67, name: "Ghar El Melh", governorate_id: 5 },
  { id: 68, name: "Ghezala", governorate_id: 5 },
  { id: 69, name: "Joumine", governorate_id: 5 },
  { id: 70, name: "Mateur", governorate_id: 5 },
  { id: 71, name: "Menzel Bourguiba", governorate_id: 5 },
  { id: 72, name: "Menzel Jemil", governorate_id: 5 },
  { id: 73, name: "Ras Jebel", governorate_id: 5 },
  { id: 74, name: "Sejnane", governorate_id: 5 },
  { id: 75, name: "Tinja", governorate_id: 5 },
  { id: 76, name: "Utique", governorate_id: 5 },
  { id: 77, name: "Zarzouna", governorate_id: 5 },
  { id: 78, name: "Gabès Médina", governorate_id: 6 },
  { id: 79, name: "Gabès Ouest", governorate_id: 6 },
  { id: 80, name: "Gabès Sud", governorate_id: 6 },
  { id: 81, name: "Ghannouch", governorate_id: 6 },
  { id: 82, name: "El Hamma", governorate_id: 6 },
  { id: 83, name: "Matmata", governorate_id: 6 },
  { id: 84, name: "Mareth", governorate_id: 6 },
  { id: 85, name: "Menzel El Habib", governorate_id: 6 },
  { id: 86, name: "Métouia", governorate_id: 6 },
  { id: 87, name: "Nouvelle Matmata", governorate_id: 6 },
  { id: 88, name: "Ariana Ville", governorate_id: 7 },
  { id: 89, name: "Ettadhamen", governorate_id: 7 },
  { id: 90, name: "Kalâat el-Andalous", governorate_id: 7 },
  { id: 91, name: "La Soukra", governorate_id: 7 },
  { id: 92, name: "Mnihla", governorate_id: 7 },
  { id: 93, name: "Raoued", governorate_id: 7 },
  { id: 94, name: "Sidi Thabet", governorate_id: 7 },
  { id: 95, name: "Ben Arous", governorate_id: 8 },
  { id: 96, name: "Bou Mhel el-Bassatine", governorate_id: 8 },
  { id: 97, name: "El Mourouj", governorate_id: 8 },
  { id: 98, name: "Ezzahra", governorate_id: 8 },
  { id: 99, name: "Fouchana", governorate_id: 8 },
  { id: 100, name: "Hammam Chott", governorate_id: 8 },
  { id: 101, name: "Hammam Lif", governorate_id: 8 },
  { id: 102, name: "Mohamedia", governorate_id: 8 },
  { id: 103, name: "Medina Jedida", governorate_id: 8 },
  { id: 104, name: "Mégrine", governorate_id: 8 },
  { id: 105, name: "Mornag", governorate_id: 8 },
  { id: 106, name: "Radès", governorate_id: 8 },
  { id: 107, name: "Belkhir", governorate_id: 9 },
  { id: 108, name: "El Guettar", governorate_id: 9 },
  { id: 109, name: "El Ksar", governorate_id: 9 },
  { id: 110, name: "Gafsa Nord", governorate_id: 9 },
  { id: 111, name: "Gafsa Sud", governorate_id: 9 },
  { id: 112, name: "Mdhilla", governorate_id: 9 },
  { id: 113, name: "Métlaoui", governorate_id: 9 },
  { id: 114, name: "Moularès", governorate_id: 9 },
  { id: 115, name: "Redeyef", governorate_id: 9 },
  { id: 116, name: "Sened", governorate_id: 9 },
  { id: 117, name: "Sidi Aïch", governorate_id: 9 },
  { id: 118, name: "Bekalta", governorate_id: 10 },
  { id: 119, name: "Bembla", governorate_id: 10 },
  { id: 120, name: "Beni Hassen", governorate_id: 10 },
  { id: 121, name: "Jemmal", governorate_id: 10 },
  { id: 122, name: "Ksar Hellal", governorate_id: 10 },
  { id: 123, name: "Ksibet el-Médiouni", governorate_id: 10 },
  { id: 124, name: "Moknine", governorate_id: 10 },
  { id: 125, name: "Monastir", governorate_id: 10 },
  { id: 126, name: "Ouerdanine", governorate_id: 10 },
  { id: 127, name: "Sahline", governorate_id: 10 },
  { id: 128, name: "Sayada-Lamta-Bou Hajar", governorate_id: 10 },
  { id: 129, name: "Téboulba", governorate_id: 10 },
  { id: 130, name: "Zéramdine", governorate_id: 10 },
  { id: 131, name: "Béni Khalled", governorate_id: 11 },
  { id: 132, name: "Béni Khiar", governorate_id: 11 },
  { id: 133, name: "Bou Argoub", governorate_id: 11 },
  { id: 134, name: "Dar Chaâbane El Fehri", governorate_id: 11 },
  { id: 135, name: "El Haouaria", governorate_id: 11 },
  { id: 136, name: "El Mida", governorate_id: 11 },
  { id: 137, name: "Grombalia", governorate_id: 11 },
  { id: 138, name: "Hammam Ghezèze", governorate_id: 11 },
  { id: 139, name: "Hammamet", governorate_id: 11 },
  { id: 140, name: "Kélibia", governorate_id: 11 },
  { id: 141, name: "Korba", governorate_id: 11 },
  { id: 142, name: "Menzel Bouzelfa", governorate_id: 11 },
  { id: 143, name: "Menzel Temime", governorate_id: 11 },
  { id: 144, name: "Nabeul", governorate_id: 11 },
  { id: 145, name: "Soliman", governorate_id: 11 },
  { id: 146, name: "Takelsa", governorate_id: 11 },
  { id: 147, name: "Ben Gardane", governorate_id: 12 },
  { id: 148, name: "Beni Khedache", governorate_id: 12 },
  { id: 149, name: "Djerba - Ajim", governorate_id: 12 },
  { id: 150, name: "Djerba - Houmt Souk", governorate_id: 12 },
  { id: 151, name: "Djerba - Midoun", governorate_id: 12 },
  { id: 152, name: "Médenine Nord", governorate_id: 12 },
  { id: 153, name: "Médenine Sud", governorate_id: 12 },
  { id: 154, name: "Sidi Makhlouf", governorate_id: 12 },
  { id: 155, name: "Zarzis", governorate_id: 12 },
  { id: 156, name: "Bir Lahmar", governorate_id: 13 },
  { id: 157, name: "Dehiba", governorate_id: 13 },
  { id: 158, name: "Ghomrassen", governorate_id: 13 },
  { id: 159, name: "Remada", governorate_id: 13 },
  { id: 160, name: "Smâr", governorate_id: 13 },
  { id: 161, name: "Tataouine Nord", governorate_id: 13 },
  { id: 162, name: "Tataouine Sud", governorate_id: 13 },
  { id: 163, name: "El Ayoun", governorate_id: 14 },
  { id: 164, name: "Ezzouhour", governorate_id: 14 },
  { id: 165, name: "Fériana", governorate_id: 14 },
  { id: 166, name: "Foussana", governorate_id: 14 },
  { id: 167, name: "Haïdra", governorate_id: 14 },
  { id: 168, name: "Hassi El Ferid", governorate_id: 14 },
  { id: 169, name: "Jedelienne", governorate_id: 14 },
  { id: 170, name: "Kasserine Nord", governorate_id: 14 },
  { id: 171, name: "Kasserine Sud", governorate_id: 14 },
  { id: 172, name: "Majel Bel Abbès", governorate_id: 14 },
  { id: 173, name: "Sbeïtla", governorate_id: 14 },
  { id: 174, name: "Sbiba", governorate_id: 14 },
  { id: 175, name: "Thala", governorate_id: 14 },
  { id: 176, name: "Manouba", governorate_id: 15 },
  { id: 177, name: "Den Den", governorate_id: 15 },
  { id: 178, name: "Douar Hicher", governorate_id: 15 },
  { id: 179, name: "Oued Ellil", governorate_id: 15 },
  { id: 180, name: "Mornaguia", governorate_id: 15 },
  { id: 181, name: "Borj El Amri", governorate_id: 15 },
  { id: 182, name: "Djedeida", governorate_id: 15 },
  { id: 183, name: "Tebourba", governorate_id: 15 },
  { id: 184, name: "El Battan", governorate_id: 15 },
  { id: 185, name: "Amdoun", governorate_id: 16 },
  { id: 186, name: "Béja Nord", governorate_id: 16 },
  { id: 187, name: "Béja Sud", governorate_id: 16 },
  { id: 188, name: "Goubellat", governorate_id: 16 },
  { id: 189, name: "Medjez el-Bab", governorate_id: 16 },
  { id: 190, name: "Nefza", governorate_id: 16 },
  { id: 191, name: "Téboursouk", governorate_id: 16 },
  { id: 192, name: "Testour", governorate_id: 16 },
  { id: 193, name: "Thibar", governorate_id: 16 },
  { id: 194, name: "Bargou", governorate_id: 17 },
  { id: 195, name: "Bou Arada", governorate_id: 17 },
  { id: 196, name: "El Aroussa", governorate_id: 17 },
  { id: 197, name: "El Krib", governorate_id: 17 },
  { id: 198, name: "Gaâfour", governorate_id: 17 },
  { id: 199, name: "Kesra", governorate_id: 17 },
  { id: 200, name: "Makthar", governorate_id: 17 },
  { id: 201, name: "Rouhia", governorate_id: 17 },
  { id: 202, name: "Sidi Bou Rouis", governorate_id: 17 },
  { id: 203, name: "Siliana Nord", governorate_id: 17 },
  { id: 204, name: "Siliana Sud", governorate_id: 17 },
  { id: 205, name: "Bir Mcherga", governorate_id: 18 },
  { id: 206, name: "El Fahs", governorate_id: 18 },
  { id: 207, name: "Nadhour", governorate_id: 18 },
  { id: 208, name: "Saouaf", governorate_id: 18 },
  { id: 209, name: "Zaghouan", governorate_id: 18 },
  { id: 210, name: "Zriba", governorate_id: 18 },
  { id: 211, name: "Douz Nord", governorate_id: 19 },
  { id: 212, name: "Douz Sud", governorate_id: 19 },
  { id: 213, name: "Faouar", governorate_id: 19 },
  { id: 214, name: "Kébili Nord", governorate_id: 19 },
  { id: 215, name: "Kébili Sud", governorate_id: 19 },
  { id: 216, name: "Souk Lahad", governorate_id: 19 },
  { id: 217, name: "Aïn Draham", governorate_id: 20 },
  { id: 218, name: "Balta-Bou Aouane", governorate_id: 20 },
  { id: 219, name: "Bou Salem", governorate_id: 20 },
  { id: 220, name: "Fernana", governorate_id: 20 },
  { id: 221, name: "Ghardimaou", governorate_id: 20 },
  { id: 222, name: "Jendouba Sud", governorate_id: 20 },
  { id: 223, name: "Jendouba Nord", governorate_id: 20 },
  { id: 224, name: "Oued Meliz", governorate_id: 20 },
  { id: 225, name: "Tabarka", governorate_id: 20 },
  { id: 226, name: "Bou Merdes", governorate_id: 21 },
  { id: 227, name: "Chebba", governorate_id: 21 },
  { id: 228, name: "Chorbane", governorate_id: 21 },
  { id: 229, name: "El Jem", governorate_id: 21 },
  { id: 230, name: "Essouassi", governorate_id: 21 },
  { id: 231, name: "Hebira", governorate_id: 21 },
  { id: 232, name: "Ksour Essef", governorate_id: 21 },
  { id: 233, name: "Mahdia", governorate_id: 21 },
  { id: 234, name: "Melloulèche", governorate_id: 21 },
  { id: 235, name: "Ouled Chamekh", governorate_id: 21 },
  { id: 236, name: "Sidi Alouane", governorate_id: 21 },
  { id: 237, name: "Rejiche", governorate_id: 21 },
  { id: 238, name: "El Bradâa", governorate_id: 21 },
  { id: 239, name: "Bir El Hafey", governorate_id: 22 },
  { id: 240, name: "Cebbala Ouled Asker", governorate_id: 22 },
  { id: 241, name: "Jilma", governorate_id: 22 },
  { id: 242, name: "Meknassy", governorate_id: 22 },
  { id: 243, name: "Menzel Bouzaiane", governorate_id: 22 },
  { id: 244, name: "Mezzouna", governorate_id: 22 },
  { id: 245, name: "Ouled Haffouz", governorate_id: 22 },
  { id: 246, name: "Regueb", governorate_id: 22 },
  { id: 247, name: "Sidi Ali Ben Aoun", governorate_id: 22 },
  { id: 248, name: "Sidi Bouzid Est", governorate_id: 22 },
  { id: 249, name: "Sidi Bouzid Ouest", governorate_id: 22 },
  { id: 250, name: "Souk Jedid", governorate_id: 22 },
  { id: 251, name: "Degache", governorate_id: 23 },
  { id: 252, name: "Hazoua", governorate_id: 23 },
  { id: 253, name: "Nefta", governorate_id: 23 },
  { id: 254, name: "Tameghza", governorate_id: 23 },
  { id: 255, name: "Tozeur", governorate_id: 23 },
  { id: 256, name: "Dahmani", governorate_id: 24 },
  { id: 257, name: "Jérissa", governorate_id: 24 },
  { id: 258, name: "El Ksour", governorate_id: 24 },
  { id: 259, name: "Sers", governorate_id: 24 },
  { id: 260, name: "Kalâat Khasba", governorate_id: 24 },
  { id: 261, name: "Kalaat Senan", governorate_id: 24 },
  { id: 262, name: "Kef Est", governorate_id: 24 },
  { id: 263, name: "Kef Ouest", governorate_id: 24 },
  { id: 264, name: "Nebeur", governorate_id: 24 },
  { id: 265, name: "Sakiet Sidi Youssef", governorate_id: 24 },
  { id: 266, name: "Tajerouine", governorate_id: 24 },
];

export { Governorate, city };
